Edit command - Nguyen
AY2324S1-CS2103T-T08-2/tp pull request #122
Opened 2023-10-23 15:34 UTC by nknguyenhc

2023-10-24 15:25 UTC, Singa-pirate requested changes
LGTM in general, just some small nitpicks to be considered.

Also, when the tags are displayed in the GUI, they are first sorted in lexicographical order. This means the tag displayed at a index may actually have a different index in the list, so editing tags can be confusing. 

I think sorting the tags in the GUI is not necessary, so I made a commit to remove the sorting. Let me know if you want to implement differently.

2023-10-24 15:25 UTC, Singa-pirate commented on src/main/java/networkbook/logic/parser/AddCommandParser.java
> +    public static AddPersonDescriptor generateEditPersonDescriptor(ArgumentMultimap argMultimap)
The method name can be changed to `generateAddPersonDescriptor`

2023-10-24 15:25 UTC, Singa-pirate commented on src/main/java/networkbook/logic/parser/AddCommandParser.java
> +        if (argMultimap.getValue(CliSyntax.PREFIX_NAME).isPresent()) {
Ideally, `AddPersonDescriptor` doesn't need to have `name` field, and instead of throwing a `CommandException` in `AddCommand#execute`, a `ParseException` can be thrown at this point. But this working implementation is ok for now.

2023-10-24 15:25 UTC, Singa-pirate commented on src/main/java/networkbook/logic/Messages.java
> +    public static final String MESSAGE_MUST_BE_PRESENT = "Since some field is present, /index must also be present.";
This message may be misleading to users since `/index` need not be present for single-value fields.

It could be changed to something like "Some field is a list that could contain multiple values. /index must be present to specify the entry".

2023-10-24 15:25 UTC, Singa-pirate commented on src/main/java/networkbook/logic/parser/EditCommandParser.java
> +        Index index = ParserUtil.parseIndex(argMultimap.getValue(CliSyntax.PREFIX_INDEX).get());
Now, if more than one `/index` is provided, it will be parsed to the last index provided.

I think it may look like a bug, and would be better if an error message is displayed if user provides more than 1 '/index'.

Same for the other `UniqueList` fields below.

2023-10-24 15:36 UTC, nknguyenhc commented on src/main/java/networkbook/logic/parser/AddCommandParser.java
> +        if (argMultimap.getValue(CliSyntax.PREFIX_NAME).isPresent()) {
Refactored from `EditPersonDescriptor`. Will make necessary changes so that add command does not accept `/name` flag.

2023-10-24 15:36 UTC, nknguyenhc commented on src/main/java/networkbook/logic/Messages.java
> +    public static final String MESSAGE_MUST_BE_PRESENT = "Since some field is present, /index must also be present.";
Will change the messages to be more specific.

2023-10-24 15:39 UTC, nknguyenhc commented on src/main/java/networkbook/logic/parser/EditCommandParser.java
> +        Index index = ParserUtil.parseIndex(argMultimap.getValue(CliSyntax.PREFIX_INDEX).get());
Will ensure that the correct number of '/index' flags is received.

2023-10-25 00:29 UTC, nknguyenhc commented
@Singa-pirate I have fixed the raised issues. However I think the error messages might have to be changed. Please advise.

2023-10-25 04:51 UTC, Singa-pirate commented
> @Singa-pirate I have fixed the raised issues. However I think the error messages might have to be changed. Please advise.

Looks great to me. The error messages are okay, I'll modify a little bit to accomodate the `delete` command in my PR later.

You can merge this PR if there are no more edits. Thanks!

2023-10-25 04:51 UTC, Singa-pirate approved these changes

2023-10-25 07:05 UTC, merged