Do QA on UG
AY2324S1-CS2103T-T08-2/tp pull request #314
Opened 2023-11-13 18:12 UTC by awhb

Closes #232

2023-11-13 19:53 UTC, Singa-pirate commented
Could you help me add the following to address issues in previous PRs:
- in the table of fields & prefixes, add input constraints for `name` (non-empty alphanumeric characters and spaces), and under remark column, say that if other characters are needed, you can get around it by omitting the required characters, as the name does not need to be the same as legal name)
- in shortcuts, add `F1` shortcut that executes the `help` command. Elaboration should be similar to ctrl-W shortcut. I think need to add an info box saying that it may not work if the `F1` shortcut has a different function in user's computer settings
- under help command, add an info box saying that if the help window is open and minimised, executing `help` command again may not make the window pop up again

Disclaimer that I have not checked your other QA changes and it does not look like I'll have time to check it tmr morning haha. Someone else please help review the changes. Thanks!

2023-11-14 01:33 UTC, nknguyenhc approved these changes
Made one small change, the rest looks ok.

2023-11-14 01:41 UTC, nknguyenhc commented on docs/UserGuide.md
> +| name                 | /name     | Any non-empty value comprising alphanumeric characters (and spaces, if any)         | Is case-sensitive                                       |
It is now not case sensitive. We have fixed this since it was indicated in UG by v1.3 that it is a fixable bug.

2023-11-14 01:42 UTC, nknguyenhc commented on docs/UserGuide.md
> +
#319 It is a fixable bug

2023-11-14 03:56 UTC, Singa-pirate requested changes
There are 2 issues with example usages:

1. `delete 1 /phone`. This contact used to have 12345679 in index 1 in a previous screenshot, but he still has the phone after the command. `delete 1 /phone /index 2` will be more appropriate.

![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/58817781/864974b5-e4c7-472c-86b8-d8b9b14b14df)

![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/58817781/a05223f0-d596-4f38-a925-bd567faa7c2d)

2. `open 3 /index 2` should be `open 2 /index 2`
![image](https://github.com/AY2324S1-CS2103T-T08-2/tp/assets/58817781/5cedadc3-2a15-4c56-a083-9e46f6a345c8)

2023-11-14 04:46 UTC, nknguyenhc approved these changes
LGTM!

2023-11-14 04:47 UTC, Singa-pirate approved these changes
LGTM!

2023-11-14 04:47 UTC, merged