Implement Add Specialisation
AY2324S1-CS2103T-T08-2/tp pull request #95
Opened 2023-10-18 05:41 UTC by Eola-Z

Since Specialisation is mostly implemented, restrict the set of valid inputs for creating Specialisation.

2023-10-18 08:28 UTC, nknguyenhc commented on src/main/java/networkbook/model/person/Specialisation.java
> +    public final String specialisation;
Please make sure that the value is not publicly accessible. Please use a getter function only.

2023-10-19 02:04 UTC, xenosf requested changes

2023-10-19 02:04 UTC, xenosf commented on src/main/java/networkbook/model/person/Specialisation.java
> +            if (!(word.matches(NOT_ALL_CAPITALIZED_REGEX) || word.matches(ALL_CAPITALIZED_REGEX))) {
This validation seems a bit too restrictive in my opinion -- can we truly guarantee specialization names will always match these restrictions? An example I can think of is those quirky abbreviations like "IoT" with capitalization that is not uniform. Even if these are not present in NUS specializations now, I don't think it's necessary to impose this specific restriction on user input especially since we are not restricting specializations in any other way.

2023-10-19 02:04 UTC, xenosf commented on src/main/java/networkbook/model/person/Specialisation.java
>       * Constructs an {@code Course}.
Please change the comments to match "specialisation" instead of "course"

2023-10-19 02:04 UTC, xenosf commented on src/test/java/networkbook/model/person/SpecialisationTest.java
> +                        + "Associations Within the Umbrella of the Multinational Party.")); // very long address
Should the "address" in the comment be "specialisation" instead?

2023-10-19 02:14 UTC, Eola-Z commented on src/main/java/networkbook/model/person/Specialisation.java
> +            if (!(word.matches(NOT_ALL_CAPITALIZED_REGEX) || word.matches(ALL_CAPITALIZED_REGEX))) {
In that case should we just specify no multiple spacing then?

2023-10-19 06:52 UTC, xenosf commented on src/main/java/networkbook/model/person/Specialisation.java
> +            if (!(word.matches(NOT_ALL_CAPITALIZED_REGEX) || word.matches(ALL_CAPITALIZED_REGEX))) {
That makes sense to me. Perhaps the spaces in beginning issue could be handled using trim()

2023-10-19 06:57 UTC, Eola-Z commented on src/main/java/networkbook/model/person/Specialisation.java
> +            if (!(word.matches(NOT_ALL_CAPITALIZED_REGEX) || word.matches(ALL_CAPITALIZED_REGEX))) {
trim() also works, let's try that instead

2023-10-19 16:03 UTC, awhb approved these changes
LGTM overall! Just note the comment left about optional fields in classes.

2023-10-19 16:03 UTC, awhb commented on src/main/java/networkbook/logic/commands/AddCommand.java
> -        Optional<Course> oldCourse = personToAddInfo.getCourse();
Jiale raised an issue that conventionally people avoid using Optional types in Java classes. We're mostly in agreement and plan to change this after v1.2. Just letting you know!

2023-10-19 16:10 UTC, xenosf approved these changes
LGTM

2023-10-19 16:12 UTC, merged